export const DEFAULT_CATEGORIES = [
  "Apartamento",
  "Carro",
  "Comida",
  "Contas Mensais",
  "Entre bancos",
  "Escritório",
  "Estudos",
  "Go On Outdoor",
  "Imposto",
  "Investimentos",
  "Lazer e ócio",
  "Pro-Labore",
  "Vida esportiva",
  "Filhos",
  "Anúncios Online",
  "Tráfego Pago",
  "Itens Físicos",
];
